### ISSUE TITLE
Basic features

### ISSUE THREAD

**Issue by piot** [coherence/installer#1]
- Command Line program for Linux, Windows and Mac in Go.

- It should install everything needed for the Coherence SDK. replication-server, unity c# code.

- __get__ : Download files from releases on Coherence GitHub and store on the local machine (e.g.extract from  `~/.coherence/install/v1.2.3/package.tar.gz` to `~/.coherence/package/v1.2.3/` ). Check integrity using a checksum.

- __list__ : List the available versions in `~/.coherence/package/`

- __select__ : Set a specified version as the active one. Which means that symlinks (in the PATH) are set to the actual installed version:
 `ln -s ~/bin/replication-server ~/.coherence/package/v1.2.3/bin/replication-server`

- Be able to report status to Unity GUI. Easiest via `stdout`.

- Ascii spinners while installer is busy.

- Future: Be able to upgrade itself

**Comment by tadej** [comment]
Checksums moved to another issue

**Comment by tadej** [comment]
Moved to new issue:
Be able to report status to Unity GUI. Easiest via stdout.
