### ISSUE TITLE
Install coherence sdk from Unity SDK Package

### ISSUE THREAD

**Issue by piot** [coherence/installer#48]
Use information inside the Unity SDK Package to install the rest of the coherence SDK environment (replication server, replication-server, packet parser, coherence cmd tool, etc)

https://github.com/coherence/unity-editor-gui/blob/master/src/lib/Editor/Config.cs

https://github.com/coherence/unity-editor-gui/blob/master/src/lib/Editor/Installer.cs

C#:
* Check, do we have a installer
* If not: Download installer
* Check if installer has a specific minimum version.
* If not: ask installer to upgrade itself.
* Start the installer and ask it to make sure that we have a specific SDK version (that is specified in a config file inside the Unity Package). in the unity project directory. The installer compares hashes or copies files from the local cache to target project directory if needed.

**Comment by gamedolphin** [comment]
Slightly different on the C# side, but this is done. 
C# side just asks the packaged installer to run everytime. The installer ensures that it exists and then exits early if it does, otherwise downloads and sets up symlinks.
