### ISSUE TITLE
Notorizing (signing) executable for MacOS

### ISSUE THREAD

**Issue by piot** [coherence/installer#60]
<img width="532" alt="Screenshot 2020-06-04 at 11 21 09" src="https://user-images.githubusercontent.com/544158/84013374-2085d480-a979-11ea-8ca1-9963f38e17f4.png">

https://github.com/mitchellh/gon
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by eriksvedang** [comment]
This is a duplicate issue, so I'll close it.
